name: BelgiumPlugin
main: me.hgk.belgiumplugin.Plugin
author: AndreasHGK
version: 1.1.1
api-version: 1.18

permissions:
  belgium:
    default: op
    children:

      reload: true

      election:
        default: op
        children:

          vote:
            default: true

          admin:
            default: op